const AUTHORIZER_CLIENT_ID = import.meta.env.VITE_AUTHORIZER_CLIENT_ID;
const CMS_URL = import.meta.env.VITE_CMS_URL;
const MUSICCODE_DOMAIN = import.meta.env.VITE_MUSICCODE_DOMAIN;
const HASURA_REST_ENDPOINT = import.meta.env.VITE_HASURA_REST_ENDPOINT;
const HASURA_GRAPHQL_ENDPOINT = import.meta.env.VITE_HASURA_GRAPHQL_ENDPOINT;
const HASURA_GRAPHQL_WEBSOCKET_ENDPOINT = import.meta.env.VITE_NATS_WEBSOCKET;
const AUTHORIZER_URL = import.meta.env.VITE_AUTHORIZER_URL;
const VITE_AUTHORIZER_REDIRECT_URL = import.meta.env.VITE_VITE_AUTHORIZER_REDIRECT_URL;

const JWT_API_KEY = "";

export {
    AUTHORIZER_URL,
    VITE_AUTHORIZER_REDIRECT_URL,
    AUTHORIZER_CLIENT_ID,
    CMS_URL,
    HASURA_REST_ENDPOINT,
    HASURA_GRAPHQL_ENDPOINT,
    HASURA_GRAPHQL_WEBSOCKET_ENDPOINT,
    JWT_API_KEY,
    MUSICCODE_DOMAIN
}

